### ISSUE TITLE
Instructions UI

### ISSUE THREAD

**Issue by j6k4m8** [aplbrain/colocar#103]
Add a `?` button. 

![image](https://user-images.githubusercontent.com/693511/43095532-27b22c84-8e84-11e8-87c8-80bf813bd11d.png)

When clicked, opens a 'drawer' from the bottom of the screen with instructions

![image](https://user-images.githubusercontent.com/693511/43095543-302895ce-8e84-11e8-8d8c-a22f96cb08ea.png)

---

**Comment by cabishop** [comment]
updated issue #185
